edit GitHub workflows

diff --git a/.github/workflows/cart-ci.yaml b/.github/workflows/cart-ci.yaml
--- a/.github/workflows/cart-ci.yaml
+++ b/.github/workflows/cart-ci.yaml
@@ -1,19 +1,19 @@
-name: cart-service ci
+name: cart service ci
 
 on:
    push:
       branches: [ "main" ]
       paths:
-         - "cart-service/**"
+         - "cart/**"
          - ".github/workflows/actions/action.yaml"
-         - ".github/workflows/cart-service-ci.yaml"
+         - ".github/workflows/cart-ci.yaml"
          - "pom.xml"
    pull_request:
       branches: [ "main" ]
       paths:
-         - "cart-service/**"
+         - "cart/**"
          - ".github/workflows/actions/action.yaml"
-         - ".github/workflows/cart-service-ci.yaml"
+         - ".github/workflows/cart-ci.yaml"
          - "pom.xml"
    workflow_dispatch:
 
@@ -28,7 +28,21 @@ jobs:
                fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          -  uses: ./.github/workflows/actions
          -  name: Run Maven Build Command
-            run: mvn clean install -pl cart-service -am -DskipTests
+            run: mvn clean install -pl cart -am -DskipTests
+         #         -  name: Run Maven Test
+         #            run: mvn test -f cart
+         #         -  name: Unit Test Results
+         #            uses: dorny/test-reporter@v1
+         #            if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' && (success() || failure()) }}
+         #            with:
+         #               name: Unit-Test-Results
+         #               path: "cart/**/surefire-reports/*.xml"
+         #               reporter: java-junit
+         #         -  name: Analyze with sonar cloud
+         #            if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+         #            env:
+         #               SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+         #            run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f cart
          -  name: Log in to the Container registry
             if: ${{ github.ref == 'refs/heads/main' }}
             uses: docker/login-action@v3
@@ -40,6 +54,6 @@ jobs:
             if: ${{ github.ref == 'refs/heads/main' }}
             uses: docker/build-push-action@v6
             with:
-               context: ./cart-service
+               context: ./cart
                push: true
-               tags: ghcr.io/hiepthanhtran/hscm-cart-service:latest
+               tags: ghcr.io/hiepthanhtran/hscms-cart:latest
diff --git a/.github/workflows/file-ci.yaml b/.github/workflows/file-ci.yaml
--- a/.github/workflows/file-ci.yaml
+++ b/.github/workflows/file-ci.yaml
@@ -1,19 +1,19 @@
-name: shipping-service ci
+name: file service ci
 
 on:
    push:
       branches: [ "main" ]
       paths:
-         - "shipping-service/**"
+         - "file/**"
          - ".github/workflows/actions/action.yaml"
-         - ".github/workflows/shipping-service-ci.yaml"
+         - ".github/workflows/file-ci.yaml"
          - "pom.xml"
    pull_request:
       branches: [ "main" ]
       paths:
-         - "shipping-service/**"
+         - "file/**"
          - ".github/workflows/actions/action.yaml"
-         - ".github/workflows/shipping-service-ci.yaml"
+         - ".github/workflows/file-ci.yaml"
          - "pom.xml"
    workflow_dispatch:
 
@@ -28,7 +28,21 @@ jobs:
                fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          -  uses: ./.github/workflows/actions
          -  name: Run Maven Build Command
-            run: mvn clean install -pl shipping-service -am -DskipTests
+            run: mvn clean install -pl file -am -DskipTests
+         #         -  name: Run Maven Test
+         #            run: mvn test -f file
+         #         -  name: Unit Test Results
+         #            uses: dorny/test-reporter@v1
+         #            if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' && (success() || failure()) }}
+         #            with:
+         #               name: Unit-Test-Results
+         #               path: "file/**/surefire-reports/*.xml"
+         #               reporter: java-junit
+         #         -  name: Analyze with sonar cloud
+         #            if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+         #            env:
+         #               SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+         #            run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f file
          -  name: Log in to the Container registry
             if: ${{ github.ref == 'refs/heads/main' }}
             uses: docker/login-action@v3
@@ -40,6 +54,6 @@ jobs:
             if: ${{ github.ref == 'refs/heads/main' }}
             uses: docker/build-push-action@v6
             with:
-               context: ./shipping-service
+               context: ./file
                push: true
-               tags: ghcr.io/hiepthanhtran/hscm-shipping-service:latest
+               tags: ghcr.io/hiepthanhtran/hscms-file:latest
diff --git a/.github/workflows/gateway-ci.yaml b/.github/workflows/gateway-ci.yaml
--- a/.github/workflows/gateway-ci.yaml
+++ b/.github/workflows/gateway-ci.yaml
@@ -1,19 +1,19 @@
-name: identity-service ci
+name: gateway service ci
 
 on:
    push:
       branches: [ "main" ]
       paths:
-         - "identity-service/**"
+         - "gateway/**"
          - ".github/workflows/actions/action.yaml"
-         - ".github/workflows/identity-service-ci.yaml"
+         - ".github/workflows/gateway-ci.yaml"
          - "pom.xml"
    pull_request:
       branches: [ "main" ]
       paths:
-         - "identity-service/**"
+         - "gateway/**"
          - ".github/workflows/actions/action.yaml"
-         - ".github/workflows/identity-service-ci.yaml"
+         - ".github/workflows/gateway-ci.yaml"
          - "pom.xml"
    workflow_dispatch:
 
@@ -28,7 +28,21 @@ jobs:
                fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          -  uses: ./.github/workflows/actions
          -  name: Run Maven Build Command
-            run: mvn clean install -pl identity-service -am -DskipTests
+            run: mvn clean install -pl gateway -am -DskipTests
+         #         -  name: Run Maven Test
+         #            run: mvn test -f gateway
+         #         -  name: Unit Test Results
+         #            uses: dorny/test-reporter@v1
+         #            if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' && (success() || failure()) }}
+         #            with:
+         #               name: Unit-Test-Results
+         #               path: "gateway/**/surefire-reports/*.xml"
+         #               reporter: java-junit
+         #         -  name: Analyze with sonar cloud
+         #            if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+         #            env:
+         #               SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+         #            run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f gateway
          -  name: Log in to the Container registry
             if: ${{ github.ref == 'refs/heads/main' }}
             uses: docker/login-action@v3
@@ -40,6 +54,6 @@ jobs:
             if: ${{ github.ref == 'refs/heads/main' }}
             uses: docker/build-push-action@v6
             with:
-               context: ./identity-service
+               context: ./gateway
                push: true
-               tags: ghcr.io/hiepthanhtran/hscm-identity-service:latest
+               tags: ghcr.io/hiepthanhtran/hscms-gateway:latest
diff --git a/.github/workflows/order-ci.yaml b/.github/workflows/order-ci.yaml
--- a/.github/workflows/order-ci.yaml
+++ b/.github/workflows/order-ci.yaml
@@ -1,19 +1,19 @@
-name: file-service ci
+name: order service ci
 
 on:
    push:
       branches: [ "main" ]
       paths:
-         - "file-service/**"
+         - "order/**"
          - ".github/workflows/actions/action.yaml"
-         - ".github/workflows/file-service-ci.yaml"
+         - ".github/workflows/order-ci.yaml"
          - "pom.xml"
    pull_request:
       branches: [ "main" ]
       paths:
-         - "file-service/**"
+         - "order/**"
          - ".github/workflows/actions/action.yaml"
-         - ".github/workflows/file-service-ci.yaml"
+         - ".github/workflows/order-ci.yaml"
          - "pom.xml"
    workflow_dispatch:
 
@@ -28,7 +28,21 @@ jobs:
                fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          -  uses: ./.github/workflows/actions
          -  name: Run Maven Build Command
-            run: mvn clean install -pl file-service -am -DskipTests
+            run: mvn clean install -pl order -am -DskipTests
+         #         -  name: Run Maven Test
+         #            run: mvn test -f order
+         #         -  name: Unit Test Results
+         #            uses: dorny/test-reporter@v1
+         #            if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' && (success() || failure()) }}
+         #            with:
+         #               name: Unit-Test-Results
+         #               path: "order/**/surefire-reports/*.xml"
+         #               reporter: java-junit
+         #         -  name: Analyze with sonar cloud
+         #            if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+         #            env:
+         #               SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+         #            run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f order
          -  name: Log in to the Container registry
             if: ${{ github.ref == 'refs/heads/main' }}
             uses: docker/login-action@v3
@@ -40,6 +54,6 @@ jobs:
             if: ${{ github.ref == 'refs/heads/main' }}
             uses: docker/build-push-action@v6
             with:
-               context: ./file-service
+               context: ./order
                push: true
-               tags: ghcr.io/hiepthanhtran/hscm-file-service:latest
+               tags: ghcr.io/hiepthanhtran/hscms-order:latest
